import type { AlgorithmInfo, GraphAlgorithmInfo, ComplexityDetail, QuizQuestion } from './index';

export const SORTING_ALGORITHMS: Record<string, AlgorithmInfo> = {
  bubble: {
    id: 'bubble',
    name: 'Bubble Sort',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    bestUseCase: 'Small datasets or nearly sorted arrays',
    description: 'Bubble Sort is the simplest sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order. The pass through the list is repeated until the list is sorted.',
    workingPrinciple: 'Repeatedly swap adjacent elements if they are in the wrong order. After each iteration, the largest unsorted element "bubbles up" to its correct position at the end.',
    pseudocode: [
      'function bubbleSort(arr):',
      '  n = arr.length',
      '  for i = 0 to n-1:',
      '    swapped = false',
      '    for j = 0 to n-i-2:',
      '      if arr[j] > arr[j+1]:',
      '        swap(arr[j], arr[j+1])',
      '        swapped = true',
      '    if not swapped:',
      '      break',
      '  return arr',
    ],
    steps: [
      'Start from the beginning of the array',
      'Compare adjacent elements',
      'If left > right, swap them',
      'Move to the next pair',
      'After each pass, the largest element reaches its correct position',
      'Repeat until no swaps are needed (array is sorted)',
    ],
    advantages: ['Simple to understand and implement', 'Stable sorting algorithm', 'In-place sorting (minimal memory)', 'Detects already-sorted arrays (O(n) best case)'],
    disadvantages: ['Very slow for large datasets', 'O(n²) average/worst case complexity', 'Much slower than other O(n²) sorts in practice'],
    commonMistakes: ['Not optimizing with the swapped flag', 'Iterating too many times (not reducing inner loop bound)', 'Using Bubble Sort for large datasets'],
    realWorldApps: ['Educational purposes', 'Small datasets where simplicity is preferred', 'When array is nearly sorted'],
    whenToUse: 'Use Bubble Sort when you need a simple implementation for small datasets or when the input is expected to be nearly sorted.',
    whenNotToUse: 'Do not use Bubble Sort for large datasets, real-time systems, or performance-critical applications.',
  },
  selection: {
    id: 'selection',
    name: 'Selection Sort',
    timeComplexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    bestUseCase: 'Small datasets where minimizing swaps is important',
    description: 'Selection Sort divides the input into a sorted and unsorted region. It repeatedly selects the smallest element from the unsorted region and moves it to the sorted region.',
    workingPrinciple: 'Find the minimum element from the unsorted portion and swap it with the first unsorted element, growing the sorted portion by one element each pass.',
    pseudocode: [
      'function selectionSort(arr):',
      '  n = arr.length',
      '  for i = 0 to n-2:',
      '    minIdx = i',
      '    for j = i+1 to n-1:',
      '      if arr[j] < arr[minIdx]:',
      '        minIdx = j',
      '    if minIdx != i:',
      '      swap(arr[i], arr[minIdx])',
      '  return arr',
    ],
    steps: [
      'Find the smallest element in the unsorted portion',
      'Swap it with the first element of the unsorted portion',
      'Expand the sorted boundary by one',
      'Repeat until the entire array is sorted',
    ],
    advantages: ['Simple to understand', 'Performs at most O(n) swaps', 'In-place sorting', 'Performance does not depend on input data'],
    disadvantages: ['Always O(n²) time complexity', 'Not stable by default', 'Slow for large datasets'],
    commonMistakes: ['Forgetting to update minIdx', 'Swapping even when minIdx == i (unnecessary swap)', 'Using on large datasets expecting good performance'],
    realWorldApps: ['When memory writes are expensive (few swaps)', 'Educational purposes', 'Small datasets'],
    whenToUse: 'Use Selection Sort when swap operations are expensive (fewer swaps than Bubble Sort) or for small datasets.',
    whenNotToUse: 'Do not use for large datasets or when stable sorting is required.',
  },
  insertion: {
    id: 'insertion',
    name: 'Insertion Sort',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    bestUseCase: 'Small or nearly sorted arrays, online sorting (sort as data arrives)',
    description: 'Insertion Sort builds the final sorted array one element at a time. It picks each element and inserts it into its correct position among the previously sorted elements.',
    workingPrinciple: 'Take one element from the unsorted portion, shift larger sorted elements to the right, and insert the element in the correct position.',
    pseudocode: [
      'function insertionSort(arr):',
      '  n = arr.length',
      '  for i = 1 to n-1:',
      '    key = arr[i]',
      '    j = i-1',
      '    while j >= 0 and arr[j] > key:',
      '      arr[j+1] = arr[j]',
      '      j = j-1',
      '    arr[j+1] = key',
      '  return arr',
    ],
    steps: [
      'Start with the second element (first element is trivially sorted)',
      'Compare current element with elements in the sorted portion',
      'Shift all larger elements one position to the right',
      'Insert the current element into its correct position',
      'Move to the next element and repeat',
    ],
    advantages: ['Simple and intuitive', 'Efficient for small or nearly sorted data', 'Stable sort', 'Online algorithm (can sort as data arrives)', 'O(n) best case'],
    disadvantages: ['O(n²) worst-case for reverse sorted', 'Not efficient for large datasets'],
    commonMistakes: ['Wrong loop bounds (starting from index 0)', 'Not shifting correctly (overwriting values)', 'Using for large unsorted datasets'],
    realWorldApps: ['Small datasets', 'Online sorting (real-time data)', 'As part of hybrid sorts (Timsort)', 'Nearly sorted data'],
    whenToUse: 'Use Insertion Sort for small datasets, nearly sorted data, or when elements arrive online one at a time.',
    whenNotToUse: 'Do not use for large, randomly distributed datasets.',
  },
  quick: {
    id: 'quick',
    name: 'Quick Sort',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)' },
    spaceComplexity: 'O(log n)',
    stable: false,
    inPlace: true,
    bestUseCase: 'Large datasets where average-case performance matters and in-place sorting is needed',
    description: 'Quick Sort selects a pivot element, partitions the array around the pivot so that smaller elements go left and larger go right, then recursively sorts the partitions.',
    workingPrinciple: 'Pick a pivot element, rearrange the array so elements less than pivot come before it and greater come after, then recursively sort the sub-arrays on either side of the pivot.',
    pseudocode: [
      'function quickSort(arr, low, high):',
      '  if low < high:',
      '    pivotIdx = partition(arr, low, high)',
      '    quickSort(arr, low, pivotIdx-1)',
      '    quickSort(arr, pivotIdx+1, high)',
      '',
      'function partition(arr, low, high):',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high-1:',
      '    if arr[j] <= pivot:',
      '      i = i + 1',
      '      swap(arr[i], arr[j])',
      '  swap(arr[i+1], arr[high])',
      '  return i+1',
    ],
    steps: [
      'Choose a pivot element (typically last element)',
      'Partition: rearrange elements around the pivot',
      'Place pivot in its final sorted position',
      'Recursively sort left sub-array (elements less than pivot)',
      'Recursively sort right sub-array (elements greater than pivot)',
    ],
    advantages: ['Fast average-case performance', 'In-place sorting (log n stack space)', 'Good cache performance', 'Can be optimized with tail recursion'],
    disadvantages: ['O(n²) worst case (bad pivot choices)', 'Not stable', 'Recursive (may cause stack overflow for large arrays)'],
    commonMistakes: ['Bad pivot selection (always first/last on sorted data)', 'Forgetting the base case', 'Incorrect partitioning logic'],
    realWorldApps: ['General-purpose sorting in many libraries', 'Database query optimization', 'Large datasets where in-place sorting matters'],
    whenToUse: 'Use Quick Sort for large datasets where average-case performance is important and in-place sorting is required.',
    whenNotToUse: 'Do not use when stable sorting is required, when data is already sorted (worst case), or when predictable performance is critical.',
  },
  heap: {
    id: 'heap',
    name: 'Heap Sort',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' },
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    bestUseCase: 'Large datasets where guaranteed O(n log n) and minimal memory is required',
    description: 'Heap Sort uses a binary heap data structure to sort elements. It first builds a max-heap from the array, then repeatedly extracts the maximum element and places it at the end.',
    workingPrinciple: 'Build a max-heap from the array, then repeatedly swap the root (maximum) with the last element, reduce heap size, and heapify the root to restore the heap property.',
    pseudocode: [
      'function heapSort(arr):',
      '  n = arr.length',
      '  for i = n/2-1 down to 0:',
      '    heapify(arr, n, i)',
      '  for i = n-1 down to 0:',
      '    swap(arr[0], arr[i])',
      '    heapify(arr, i, 0)',
      '',
      'function heapify(arr, n, i):',
      '  largest = i',
      '  left = 2*i + 1',
      '  right = 2*i + 2',
      '  if left < n and arr[left] > arr[largest]:',
      '    largest = left',
      '  if right < n and arr[right] > arr[largest]:',
      '    largest = right',
      '  if largest != i:',
      '    swap(arr[i], arr[largest])',
      '    heapify(arr, n, largest)',
    ],
    steps: [
      'Build a max-heap from the input array',
      'Swap the root (largest element) with the last element',
      'Reduce heap size by 1',
      'Heapify the new root to restore max-heap property',
      'Repeat until all elements are sorted',
    ],
    advantages: ['Guaranteed O(n log n) time', 'In-place sorting (no extra memory)', 'No recursion overhead', 'Better worst-case than Quick Sort'],
    disadvantages: ['Not stable', 'Slower constant factors than Quick Sort on average', 'Not adaptive (same speed for all inputs)'],
    commonMistakes: ['Incorrect heapify index calculation', 'Forgetting to reduce heap size after extraction', 'Building heap with wrong loop bounds'],
    realWorldApps: ['When guaranteed performance is needed', 'Memory-constrained environments', 'Priority queue implementations'],
    whenToUse: 'Use Heap Sort when guaranteed O(n log n) performance and O(1) extra memory are both required.',
    whenNotToUse: 'Do not use when stable sorting is needed or when average-case performance of Quick Sort is preferred.',
  },
};

export const GRAPH_ALGORITHMS: Record<string, GraphAlgorithmInfo & { graphType: 'unweighted' | 'weighted' }> = {
  bfs: {
    id: 'bfs',
    name: 'Breadth First Search',
    graphType: 'unweighted',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    inPlace: false,
    bestUseCase: 'Finding shortest path in unweighted graphs, level-order traversal',
    description: 'BFS explores a graph level by level. It starts at a source node and visits all nodes at the present depth before moving to nodes at the next depth level.',
    workingPrinciple: 'Use a queue to visit nodes in FIFO order. Visit all neighbors of the current node before going deeper.',
    pseudocode: [
      'function BFS(graph, start):',
      '  queue = [start]',
      '  visited = {start}',
      '  while queue is not empty:',
      '    node = queue.dequeue()',
      '    for neighbor in graph[node]:',
      '      if neighbor not in visited:',
      '        visited.add(neighbor)',
      '        queue.enqueue(neighbor)',
      '  return visited',
    ],
    steps: [
      'Start at the source node, mark as visited and enqueue',
      'While queue is not empty: dequeue a node',
      'Visit all unvisited neighbors of the node',
      'Mark each neighbor as visited and enqueue it',
      'Continue until queue is empty',
    ],
    applications: ['Shortest path in unweighted graphs', 'Web crawling', 'Social networks', 'GPS navigation', 'Peer-to-peer networks'],
    advantages: ['Guaranteed shortest path in unweighted graphs', 'Complete - explores all reachable nodes', 'Intuitive level-order traversal'],
    disadvantages: ['Requires O(V) memory for queue', 'Not suitable for weighted graphs', 'May explore unnecessary nodes in large graphs'],
    commonMistakes: ['Forgetting to mark nodes as visited when enqueuing', 'Using a stack instead of a queue', 'Not handling disconnected graphs'],
    realWorldApps: ['Finding shortest paths', 'Social network connections (degrees of separation)', 'Web crawling', 'Broadcasting in networks'],
    whenToUse: 'Use BFS for finding the shortest path in unweighted graphs, level-order traversal, or exploring all nodes reachable from a source.',
    whenNotToUse: 'Do not use BFS for weighted graphs (use Dijkstra), when memory is limited (queue may grow large), or when depth matters more than breadth.',
  },
  dfs: {
    id: 'dfs',
    name: 'Depth First Search',
    graphType: 'unweighted',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    inPlace: false,
    bestUseCase: 'Exploring all nodes, detecting cycles, topological sorting, path finding',
    description: 'DFS explores a graph by going as deep as possible along each branch before backtracking.',
    workingPrinciple: 'Use a stack (or recursion) to visit nodes in LIFO order. Go deep into one neighbor before exploring others.',
    pseudocode: [
      'function DFS(graph, start):',
      '  stack = [start]',
      '  visited = {start}',
      '  while stack is not empty:',
      '    node = stack.pop()',
      '    for neighbor in graph[node]:',
      '      if neighbor not in visited:',
      '        visited.add(neighbor)',
      '        stack.push(neighbor)',
      '  return visited',
    ],
    steps: [
      'Start at source node, mark as visited and push to stack',
      'While stack is not empty: pop a node',
      'Visit all unvisited neighbors of the node',
      'Mark each neighbor as visited and push to stack',
      'Continue until stack is empty',
    ],
    applications: ['Cycle detection in graphs', 'Topological sorting', 'Solving puzzles (mazes)', 'Graph connectivity', 'Finding strongly connected components'],
    advantages: ['Uses less memory when the graph is deep (vs BFS)', 'Good for decision trees and mazes', 'Can detect cycles easily', 'Natural for recursive problems'],
    disadvantages: ['May go too deep (stack overflow)', 'Not guaranteed to find shortest path', 'May get stuck in infinite loops without visited tracking'],
    commonMistakes: ['Not marking nodes as visited when pushing to stack', 'Forgetting to handle disconnected components', 'Stack overflow in recursion for deep graphs'],
    realWorldApps: ['Maze solving', 'Cycle detection', 'Topological sorting in build systems', 'Web crawling (limited depth)'],
    whenToUse: 'Use DFS for exploring all paths, detecting cycles, topological sorting, or when memory is limited (deep but narrow graphs).',
    whenNotToUse: 'Do not use DFS for finding shortest paths in unweighted graphs (use BFS) or weighted graphs (use Dijkstra).',
  },
  dijkstra: {
    id: 'dijkstra',
    name: "Dijkstra's Algorithm",
    graphType: 'weighted',
    timeComplexity: { best: 'O(V + E log V)', average: 'O(V + E log V)', worst: 'O(V + E log V)' },
    spaceComplexity: 'O(V)',
    stable: true,
    inPlace: false,
    bestUseCase: 'Finding shortest paths in weighted graphs with non-negative edge weights',
    description: "Dijkstra's algorithm finds the shortest path from a source node to all other nodes in a weighted graph with non-negative edge weights.",
    workingPrinciple: 'Maintain distances from source. Use a min-priority queue to always expand the closest unvisited node. Relax edges and update distances.',
    pseudocode: [
      'function Dijkstra(graph, start):',
      '  dist[start] = 0',
      '  for each node v != start:',
      '    dist[v] = INFINITY',
      '  pq = min-priority queue ordered by dist',
      '  pq.insert(start, 0)',
      '  while pq is not empty:',
      '    (node, d) = pq.extractMin()',
      '    if d > dist[node]: continue',
      '    for (neighbor, weight) in graph[node]:',
      '      newDist = dist[node] + weight',
      '      if newDist < dist[neighbor]:',
      '        dist[neighbor] = newDist',
      '        pq.insert(neighbor, newDist)',
      '  return dist',
    ],
    steps: [
      'Initialize all distances to INFINITY, source distance to 0',
      'Insert source into min-priority queue with distance 0',
      'Extract node with minimum distance from queue',
      'For each neighbor, calculate new distance through current node',
      'If new distance is smaller, update and insert into queue',
      'Repeat until queue is empty',
    ],
    applications: ['GPS navigation and maps', 'Network routing protocols', 'Social network analysis', 'Logistics and transportation'],
    advantages: ['Finds shortest path in weighted graphs', 'Works well with positive weights', 'Can be optimized with priority queue', 'Guarantees optimal solution'],
    disadvantages: ['Does not work with negative edge weights', 'Requires O(V) extra memory', 'Slower than BFS on unweighted graphs', 'Priority queue overhead'],
    commonMistakes: ['Using a simple queue instead of a priority queue', 'Not checking if extracted distance is outdated', 'Not handling disconnected nodes', 'Using with negative edge weights'],
    realWorldApps: ['Google Maps', 'Network routing (OSPF)', 'Flight booking systems', 'Supply chain optimization'],
    whenToUse: "Use Dijkstra when you need the shortest path in a graph with non-negative edge weights. Ideal for routing and navigation problems.",
    whenNotToUse: "Do not use Dijkstra with negative edge weights (use Bellman-Ford). For unweighted graphs, BFS is more efficient.",
  },
};

export const SORTING_ALGORITHM_KEYS = Object.keys(SORTING_ALGORITHMS);
export const GRAPH_ALGORITHM_KEYS = Object.keys(GRAPH_ALGORITHMS);

export const COMPLEXITY_DETAILS: Record<string, ComplexityDetail[]> = {
  bubble: [
    {
      case: 'best',
      notation: 'O(n)',
      explanation: ['The best case occurs when the array is already sorted.', 'In this case, we only need one pass through the array to confirm it is sorted.', 'No swaps are performed during this pass.'],
      lineByLine: [
        { line: 'for i = 0 to n-1:', cost: 'O(1)', count: '1 pass' },
        { line: '  swapped = false', cost: 'O(1)', count: '1' },
        { line: '  for j = 0 to n-i-2:', cost: 'O(1)', count: 'n-1 comparisons' },
        { line: '    if arr[j] > arr[j+1]:', cost: 'O(1)', count: 'n-1' },
        { line: '      swap(arr[j], arr[j+1])', cost: 'O(1)', count: '0 (no swaps)' },
        { line: '  if not swapped: break', cost: 'O(1)', count: '1' },
      ],
      derivation: ['Total operations = (n-1) comparisons + O(1) overhead', 'Since the array is sorted, only one pass is needed', 'Time complexity = O(n)'],
    },
    {
      case: 'average',
      notation: 'O(n²)',
      explanation: ['The average case occurs with randomly ordered arrays.', 'On average, about half the elements are out of place.', 'We need roughly n/2 passes with n/2 comparisons each.'],
      lineByLine: [
        { line: 'for i = 0 to n-1:', cost: 'O(1)', count: '~n/2 passes' },
        { line: '  swapped = false', cost: 'O(1)', count: '~n/2' },
        { line: '  for j = 0 to n-i-2:', cost: 'O(1)', count: '~n/2 comparisons avg' },
        { line: '    if arr[j] > arr[j+1]:', cost: 'O(1)', count: '~n/2' },
        { line: '      swap(arr[j], arr[j+1])', cost: 'O(1)', count: '~n/4' },
      ],
      derivation: ['Total comparisons ≈ (n/2) × (n/2) = n²/4', 'Total swaps ≈ n²/8', 'After removing constants: O(n²)'],
    },
    {
      case: 'worst',
      notation: 'O(n²)',
      explanation: ['The worst case occurs when the array is reverse sorted.', 'Every element must be compared and swapped in every pass.', 'n passes with n-i-1 comparisons per pass.'],
      lineByLine: [
        { line: 'for i = 0 to n-1:', cost: 'O(1)', count: 'n passes' },
        { line: '  swapped = false', cost: 'O(1)', count: 'n' },
        { line: '  for j = 0 to n-i-2:', cost: 'O(1)', count: 'n-1, n-2, ..., 1' },
        { line: '    if arr[j] > arr[j+1]:', cost: 'O(1)', count: 'sum of (n-i-1) for i=0..n-1' },
        { line: '      swap(arr[j], arr[j+1])', cost: 'O(1)', count: 'same as comparisons' },
      ],
      derivation: ['Total comparisons = (n-1) + (n-2) + ... + 1 = n(n-1)/2', 'Total swaps = n(n-1)/2', 'Time complexity = O(n²)'],
    },
  ],
  quick: [
    {
      case: 'best',
      notation: 'O(n log n)',
      explanation: ['The best case occurs when the pivot always divides the array into two equal halves.', 'This happens when the pivot is always the median element.', 'This results in balanced partitioning similar to Merge Sort.'],
      lineByLine: [
        { line: 'function quickSort(arr, low, high):', cost: 'O(1)', count: '1' },
        { line: '  if low < high:', cost: 'O(1)', count: 'per call' },
        { line: '    pivotIdx = partition(arr, low, high)', cost: 'O(n)', count: 'per level' },
        { line: '    quickSort(arr, low, pivotIdx-1)', cost: 'T(n/2)', count: 'n/2' },
        { line: '    quickSort(arr, pivotIdx+1, high)', cost: 'T(n/2)', count: 'n/2' },
      ],
      recurrenceRelation: 'T(n) = 2T(n/2) + O(n)',
      recursionTree: [
        'Level 0: Size n, partition cost O(n)',
        'Level 1: Two subproblems of size n/2, total partition cost O(n)',
        'Level 2: Four subproblems of size n/4, total cost O(n)',
        '...',
        'Height = log₂(n) (balanced)',
        'Total cost = O(n log n)',
      ],
      derivation: ['T(n) = 2T(n/2) + O(n)', 'Same recurrence as Merge Sort', 'By Master Theorem: T(n) = Θ(n log n)'],
    },
    {
      case: 'average',
      notation: 'O(n log n)',
      explanation: ['On average, random pivot selection creates reasonably balanced partitions.', 'The expected depth of recursion is O(log n).', 'The total expected comparisons is O(n log n).'],
      lineByLine: [
        { line: 'function quickSort(arr, low, high):', cost: 'O(1)', count: '1' },
        { line: '  pivotIdx = partition(arr, low, high)', cost: 'O(n)', count: 'on average O(n)' },
        { line: '    quickSort left half', cost: 'T(n/2)', count: '~n/2 on average' },
        { line: '    quickSort right half', cost: 'T(n/2)', count: '~n/2 on average' },
      ],
      recurrenceRelation: 'T(n) = T(k) + T(n-k-1) + O(n) where k is the number of elements less than pivot',
      recursionTree: [
        'On average, pivot falls near the middle',
        'Expected partition sizes: n/4 and 3n/4 in worst-case average',
        'Average depth: O(log n)',
        'Total comparisons: O(n log n)',
      ],
      derivation: ['Using probabilistic analysis: T(n) = (1/n) * Σ(k=0 to n-1) [T(k) + T(n-k-1)] + cn', 'This solves to T(n) ≈ 2n ln n = O(n log n)', 'Average case is O(n log n) with a higher constant than best case'],
    },
    {
      case: 'worst',
      notation: 'O(n²)',
      explanation: ['The worst case occurs when the pivot is always the smallest or largest element.', 'This happens when the array is already sorted and pivot is the first or last element.', 'Each partition creates a subproblem of size n-1 and another of size 0.'],
      lineByLine: [
        { line: 'function partition(arr, low, high):', cost: 'O(1)', count: '1' },
        { line: '  for j = low to high-1:', cost: 'O(1)', count: 'n comparisons' },
        { line: '    if arr[j] <= pivot:', cost: 'O(1)', count: 'n' },
        { line: '      swap(arr[i], arr[j])', cost: 'O(1)', count: '0 (always smallest/largest)' },
        { line: 'quickSort(arr, low, pivotIdx-1)', cost: 'T(0) = O(1)', count: '0' },
        { line: 'quickSort(arr, pivotIdx+1, high)', cost: 'T(n-1)', count: 'n-1' },
      ],
      recurrenceRelation: 'T(n) = T(n-1) + O(n)',
      recursionTree: [
        'Level 0: Size n, cost O(n)',
        'Level 1: Size n-1, cost O(n-1)',
        'Level 2: Size n-2, cost O(n-2)',
        '...',
        'Level n-1: Size 1, cost O(1)',
        'This forms a linear chain, not a balanced tree!',
      ],
      derivation: ['T(n) = T(n-1) + n', 'T(n-1) = T(n-2) + (n-1)', '...', 'T(2) = T(1) + 2', 'Summing: T(n) = n + (n-1) + (n-2) + ... + 2 + T(1)', 'T(n) = n(n+1)/2 - 1 = O(n²)'],
    },
  ],
  selection: [
    {
      case: 'best',
      notation: 'O(n²)',
      explanation: ['Selection Sort always performs the same number of comparisons regardless of input order.', 'Even if the array is sorted, it still searches for the minimum in each pass.'],
      lineByLine: [
        { line: 'for i = 0 to n-2:', cost: 'O(1)', count: 'n-1 passes' },
        { line: '  minIdx = i', cost: 'O(1)', count: 'n-1' },
        { line: '  for j = i+1 to n-1:', cost: 'O(1)', count: 'n-1, n-2, ... 1' },
        { line: '    if arr[j] < arr[minIdx]:', cost: 'O(1)', count: 'total n(n-1)/2' },
        { line: '  swap(arr[i], arr[minIdx])', cost: 'O(1)', count: 'n-1 swaps' },
      ],
      derivation: ['Comparisons = (n-1)+(n-2)+...+1 = n(n-1)/2 = O(n²)', 'Swaps = n-1 = O(n)', 'Overall complexity = O(n²) (dominated by comparisons)'],
    },
    {
      case: 'average',
      notation: 'O(n²)',
      explanation: ['The number of comparisons is always the same, regardless of input ordering.', 'Average case is identical to best and worst cases.'],
      lineByLine: [
        { line: 'for i = 0 to n-2:', cost: 'O(1)', count: 'n-1 passes' },
        { line: '  minIdx = i', cost: 'O(1)', count: 'n-1' },
        { line: '  for j = i+1 to n-1:', cost: 'O(1)', count: 'total n(n-1)/2' },
        { line: '    if arr[j] < arr[minIdx]:', cost: 'O(1)', count: 'n(n-1)/2' },
        { line: '  swap(arr[i], arr[minIdx])', cost: 'O(1)', count: 'n-1' },
      ],
      derivation: ['Total comparisons = n(n-1)/2', 'Total swaps = n-1', 'Time complexity = O(n²)'],
    },
    {
      case: 'worst',
      notation: 'O(n²)',
      explanation: ['Same as best and average cases - Selection Sort is not adaptive.', 'It always performs exactly n(n-1)/2 comparisons.'],
      lineByLine: [
        { line: 'for i = 0 to n-2:', cost: 'O(1)', count: 'n-1 passes' },
        { line: '  minIdx = i', cost: 'O(1)', count: 'n-1' },
        { line: '  for j = i+1 to n-1:', cost: 'O(1)', count: 'total n(n-1)/2' },
        { line: '    if arr[j] < arr[minIdx]:', cost: 'O(1)', count: 'n(n-1)/2' },
        { line: '  swap(arr[i], arr[minIdx])', cost: 'O(1)', count: 'n-1' },
      ],
      derivation: ['Number of comparisons: Σ(i=1 to n-1) of i = n(n-1)/2', 'This is always O(n²) regardless of input order'],
    },
  ],
  insertion: [
    {
      case: 'best',
      notation: 'O(n)',
      explanation: ['The best case occurs when the array is already sorted.', 'Each element is already in the correct position.', 'The while loop condition fails immediately for each element.'],
      lineByLine: [
        { line: 'for i = 1 to n-1:', cost: 'O(1)', count: 'n-1' },
        { line: '  key = arr[i]', cost: 'O(1)', count: 'n-1' },
        { line: '  j = i-1', cost: 'O(1)', count: 'n-1' },
        { line: '  while j >= 0 and arr[j] > key:', cost: 'O(1)', count: '1 comparison each (fails immediately)' },
        { line: '    arr[j+1] = arr[j]', cost: 'O(1)', count: '0 (no shifts)' },
        { line: '  arr[j+1] = key', cost: 'O(1)', count: 'n-1' },
      ],
      derivation: ['Total operations = n-1 comparisons + overhead = O(n)', 'This is because arr[j] > key is false immediately for each element'],
    },
    {
      case: 'average',
      notation: 'O(n²)',
      explanation: ['On average, each element needs to shift about half of the already sorted elements.', 'For random data, the inner while loop runs approximately i/2 times for the i-th element.'],
      lineByLine: [
        { line: 'for i = 1 to n-1:', cost: 'O(1)', count: 'n-1' },
        { line: '  key = arr[i]', cost: 'O(1)', count: 'n-1' },
        { line: '  j = i-1', cost: 'O(1)', count: 'n-1' },
        { line: '  while j >= 0 and arr[j] > key:', cost: 'O(1)', count: '~i/2 comparisons on average' },
        { line: '    arr[j+1] = arr[j]', cost: 'O(1)', count: '~i/2 shifts' },
        { line: '  arr[j+1] = key', cost: 'O(1)', count: 'n-1' },
      ],
      derivation: ['Total comparisons ≈ Σ(i=1 to n-1) i/2 = (n-1)n/4 = O(n²)', 'Average case is O(n²)'],
    },
    {
      case: 'worst',
      notation: 'O(n²)',
      explanation: ['The worst case occurs when the array is reverse sorted.', 'Each element must be compared with all previously sorted elements.', 'The inner while loop runs i times for the i-th element.'],
      lineByLine: [
        { line: 'for i = 1 to n-1:', cost: 'O(1)', count: 'n-1' },
        { line: '  key = arr[i]', cost: 'O(1)', count: 'n-1' },
        { line: '  j = i-1', cost: 'O(1)', count: 'n-1' },
        { line: '  while j >= 0 and arr[j] > key:', cost: 'O(1)', count: 'i comparisons for each i' },
        { line: '    arr[j+1] = arr[j]', cost: 'O(1)', count: 'i shifts for each i' },
        { line: '  arr[j+1] = key', cost: 'O(1)', count: 'n-1' },
      ],
      derivation: ['Total comparisons = 1 + 2 + 3 + ... + (n-1) = n(n-1)/2', 'Total shifts = n(n-1)/2', 'Time complexity = O(n²)'],
    },
  ],
  heap: [
    {
      case: 'best',
      notation: 'O(n log n)',
      explanation: ['Building a heap takes O(n) time.', 'Each extraction (heapify) takes O(log n) time.', 'Extracting all n elements takes O(n log n) total.'],
      lineByLine: [
        { line: 'for i = n/2-1 down to 0: heapify', cost: 'O(n)', count: 'building heap takes O(n)' },
        { line: 'for i = n-1 down to 0:', cost: 'O(1)', count: 'n iterations' },
        { line: '  swap(arr[0], arr[i])', cost: 'O(1)', count: 'n swaps' },
        { line: '  heapify(arr, i, 0)', cost: 'O(log n)', count: 'n times, each O(log n)' },
      ],
      derivation: ['Build heap: O(n)', 'n extractions × O(log n) each = O(n log n)', 'Total: O(n) + O(n log n) = O(n log n)'],
    },
    {
      case: 'average',
      notation: 'O(n log n)',
      explanation: ['Heap Sort has the same complexity regardless of input order.', 'The heapify operation always takes O(log n) time on average.'],
      lineByLine: [
        { line: 'Build max-heap', cost: 'O(n)', count: 'always O(n)' },
        { line: 'for i = n-1 down to 0:', cost: 'O(1)', count: 'n iterations' },
        { line: '  swap + heapify', cost: 'O(log n)', count: 'n times' },
      ],
      derivation: ['Build heap: O(n)', 'Extraction phase: O(n log n)', 'Total: O(n log n)'],
    },
    {
      case: 'worst',
      notation: 'O(n log n)',
      explanation: ['Heap Sort is one of the few sorts with O(n log n) worst-case guarantee.', 'Even in the worst case, heapify operations take O(log n).'],
      lineByLine: [
        { line: 'Build max-heap', cost: 'O(n)', count: 'always O(n)' },
        { line: 'for i = n-1 down to 0:', cost: 'O(1)', count: 'n iterations' },
        { line: '  swap + heapify', cost: 'O(log n)', count: 'n times, each O(log n)' },
      ],
      derivation: ['Build heap: O(n) always', 'Each heapify can traverse entire tree height: O(log n)', 'Total: O(n log n) guaranteed'],
    },
  ],
};

export const GRAPH_COMPLEXITY_DETAILS: Record<string, ComplexityDetail[]> = {
  bfs: [
    {
      case: 'best',
      notation: 'O(V + E)',
      explanation: ['BFS must visit every reachable node and traverse its edges.', 'In the best case, starting node may have no neighbors, but we still visit it.', 'Time is always proportional to V + E for the reachable component.'],
      lineByLine: [
        { line: 'queue = [start]; visited = {start}', cost: 'O(1)', count: '1' },
        { line: 'while queue is not empty:', cost: 'O(1)', count: 'V times (each node once)' },
        { line: '  node = queue.dequeue()', cost: 'O(1)', count: 'V times' },
        { line: '  for neighbor in graph[node]:', cost: 'O(1)', count: '2E times (each edge twice)' },
        { line: '    if neighbor not visited:', cost: 'O(1)', count: 'E times (each edge once)' },
        { line: '      visited.add(neighbor)', cost: 'O(1)', count: 'V times (each node once)' },
        { line: '      queue.enqueue(neighbor)', cost: 'O(1)', count: 'V times' },
      ],
      derivation: ['Each node is enqueued/dequeued exactly once: O(V)', 'Each edge is examined twice (once from each endpoint): O(E)', 'Total: O(V) + O(E) = O(V + E)'],
    },
    {
      case: 'average',
      notation: 'O(V + E)',
      explanation: ['BFS always processes all reachable nodes and their incident edges.', 'The average case is the same as best and worst cases.'],
      lineByLine: [
        { line: 'Each node visited once', cost: 'O(V)', count: 'V' },
        { line: 'Each edge traversed once', cost: 'O(E)', count: 'E' },
      ],
      derivation: ['Total = O(V + E) for any connected component'],
    },
    {
      case: 'worst',
      notation: 'O(V + E)',
      explanation: ['In the worst case, all nodes are reachable from the start.', 'All edges are examined.', 'Time = O(V + E), which is optimal for graph traversal.'],
      lineByLine: [
        { line: 'Each node enqueued exactly once', cost: 'O(1)', count: 'V' },
        { line: 'Each edge examined exactly twice', cost: 'O(1)', count: '2E' },
      ],
      derivation: ['Processing each node: O(V)', 'Processing each edge: O(E)', 'Total: O(V + E)'],
    },
  ],
  dfs: [
    {
      case: 'best',
      notation: 'O(V + E)',
      explanation: ['Similar to BFS, DFS must visit each reachable node and traverse its edges.', 'The time complexity depends on the graph size, not the order of traversal.'],
      lineByLine: [
        { line: 'stack = [start]; visited = {start}', cost: 'O(1)', count: '1' },
        { line: 'while stack is not empty:', cost: 'O(1)', count: 'V times' },
        { line: '  node = stack.pop()', cost: 'O(1)', count: 'V times' },
        { line: '  for neighbor in graph[node]:', cost: 'O(1)', count: '2E times' },
        { line: '    if neighbor not visited:', cost: 'O(1)', count: 'E times' },
        { line: '      visited.add(neighbor)', cost: 'O(1)', count: 'V times' },
        { line: '      stack.push(neighbor)', cost: 'O(1)', count: 'V times' },
      ],
      derivation: ['Each node is pushed/popped exactly once: O(V)', 'Each edge is examined twice: O(E)', 'Total: O(V + E)'],
    },
    {
      case: 'average',
      notation: 'O(V + E)',
      explanation: ['DFS always visits all nodes and edges in the reachable component.', 'The average case matches best and worst cases.'],
      lineByLine: [
        { line: 'Each node visited once', cost: 'O(V)', count: 'V' },
        { line: 'Each edge examined once', cost: 'O(E)', count: 'E' },
      ],
      derivation: ['Total = O(V + E)'],
    },
    {
      case: 'worst',
      notation: 'O(V + E)',
      explanation: ['DFS visits all reachable nodes and traverses all edges.', 'The worst case is when the entire graph is reachable from the start node.'],
      lineByLine: [
        { line: 'Each node pushed/popped once', cost: 'O(1)', count: 'V' },
        { line: 'Each edge examined twice', cost: 'O(1)', count: '2E' },
      ],
      derivation: ['Processing all nodes: O(V)', 'Processing all edges: O(E)', 'Total: O(V + E)'],
    },
  ],
  dijkstra: [
    {
      case: 'best',
      notation: 'O(V + E log V)',
      explanation: ['With a binary heap priority queue, each extract-min and decrease-key takes O(log V).', 'Each node is extracted once: O(V log V)', 'Each edge is relaxed once: O(E log V)'],
      lineByLine: [
        { line: 'dist[start] = 0; pq.insert(start, 0)', cost: 'O(log V)', count: '1' },
        { line: 'while pq is not empty:', cost: 'O(1)', count: 'V times' },
        { line: '  (node, d) = pq.extractMin()', cost: 'O(log V)', count: 'V times' },
        { line: '  for (neighbor, weight):', cost: 'O(1)', count: 'E times (total)' },
        { line: '    newDist = dist[node] + weight', cost: 'O(1)', count: 'E times' },
        { line: '    if newDist < dist[neighbor]:', cost: 'O(1)', count: 'E times' },
        { line: '      dist[neighbor] = newDist', cost: 'O(1)', count: 'E times' },
        { line: '      pq.insert(neighbor, newDist)', cost: 'O(log V)', count: 'E times (worst-case)' },
      ],
      derivation: ['Extract-min operations: V × O(log V) = O(V log V)', 'Priority queue insertions: E × O(log V) = O(E log V)', 'Total: O(V log V + E log V) = O(V + E log V) [when E ≥ V]', 'The priority queue adds O(log V) factor compared to BFS/DFS'],
    },
    {
      case: 'average',
      notation: 'O(V + E log V)',
      explanation: ['On average, each node has degree E/V.', 'Priority queue operations remain O(log V) on average.'],
      lineByLine: [
        { line: 'Initialize distances', cost: 'O(V)', count: 'V' },
        { line: 'Priority queue operations', cost: 'O(log V) each', count: 'V + E' },
        { line: 'Edge relaxation', cost: 'O(1)', count: 'E' },
      ],
      derivation: ['Total = O(V) + O((V+E) log V) = O(V + E log V)'],
    },
    {
      case: 'worst',
      notation: 'O(V + E log V)',
      explanation: ['The priority queue is the key factor in Dijkstra\'s complexity.', 'Without a priority queue (using simple array), the complexity would be O(V²).', 'With a binary heap, each operation is O(log V).', 'Using a Fibonacci heap could reduce this to O(V log V + E).'],
      lineByLine: [
        { line: 'V extract-min operations', cost: 'O(log V) each', count: 'V' },
        { line: 'E priority queue insertions/updates', cost: 'O(log V) each', count: 'E' },
        { line: 'E edge relaxations', cost: 'O(1) each', count: 'E' },
      ],
      derivation: ['Without priority queue: O(V²) (using simple array for min-finding)', 'With binary heap: O((V+E) log V) = O(E log V) for dense graphs', 'With Fibonacci heap: O(V log V + E)', 'The priority queue is essential for efficiency!', 'It allows us to find the node with minimum distance in O(log V) instead of O(V)'],
    },
  ],
};

export const SORTING_QUIZZES: Record<string, QuizQuestion[]> = {
  bubble: [
    { question: 'What is the best-case time complexity of Bubble Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], correctIndex: 0, explanation: 'When the array is already sorted, Bubble Sort makes one pass with no swaps: O(n).' },
    { question: 'How does the optimized Bubble Sort detect that the array is already sorted?', options: ['It checks if first element < last element', 'It uses a swapped flag that remains false', 'It counts the number of inversions', 'It uses binary search'], correctIndex: 1, explanation: 'If no swaps occur in a complete pass, the swapped flag stays false and the algorithm terminates early.' },
    { question: 'Is Bubble Sort a stable sorting algorithm?', options: ['Yes', 'No', 'Only in worst case', 'Only in best case'], correctIndex: 0, explanation: "Bubble Sort is stable because it only swaps adjacent elements when the left is greater than the right (not greater or equal)." },
    { question: 'What is the worst-case time complexity of Bubble Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2^n)'], correctIndex: 2, explanation: 'When the array is reverse sorted, Bubble Sort needs n passes with n-i-1 comparisons each: total O(n²).' },
    { question: 'In the worst case, how many comparisons does Bubble Sort make for an array of size n?', options: ['n-1', 'n', 'n(n-1)/2', 'n²'], correctIndex: 2, explanation: 'Worst case: (n-1)+(n-2)+...+1 = n(n-1)/2 comparisons.' },
    { question: 'What is the space complexity of Bubble Sort?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], correctIndex: 0, explanation: 'Bubble Sort sorts in-place using only a constant amount of extra space (temp variable for swaps).' },
    { question: 'Why is Bubble Sort considered inefficient for large datasets?', options: ['It has O(n²) complexity', 'It uses too much memory', 'It cannot handle negative numbers', 'It is unstable'], correctIndex: 0, explanation: 'For large n, O(n²) means the number of operations grows quadratically, making it impractical for n > 10,000.' },
    { question: 'What happens to Bubble Sort if the array is already sorted with the optimization?', options: ['It still does n passes', 'It completes in O(n) time', 'It crashes', 'It becomes unstable'], correctIndex: 1, explanation: 'The swapped flag optimization detects that no swaps were needed and terminates after the first pass.' },
  ],
  quick: [
    { question: 'What is the worst-case time complexity of Quick Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2^n)'], correctIndex: 2, explanation: 'When the pivot is always the smallest or largest element (e.g., sorted array with first/last pivot), Quick Sort degrades to O(n²).' },
    { question: 'What operation in Quick Sort is responsible for rearranging elements?', options: ['Merging', 'Partitioning', 'Heapifying', 'Swapping'], correctIndex: 1, explanation: 'The partition function rearranges elements around the pivot so smaller elements go left and larger go right.' },
    { question: 'What is the best-case recurrence for Quick Sort?', options: ['T(n) = T(n-1) + O(n)', 'T(n) = 2T(n/2) + O(n)', 'T(n) = 2T(n/2) + O(1)', 'T(n) = T(n/2) + O(n)'], correctIndex: 1, explanation: 'With balanced partitioning, Quick Sort has the same recurrence as Merge Sort: T(n) = 2T(n/2) + O(n).' },
    { question: 'How can Quick Sort be optimized to avoid worst-case behavior?', options: ['Use first element as pivot', 'Use median-of-three pivot selection', 'Use last element as pivot', 'Use a random pivot or median-of-three'], correctIndex: 3, explanation: 'Random pivot selection or median-of-three makes the worst case extremely unlikely.' },
    { question: 'Is Quick Sort stable?', options: ['Yes', 'No', 'Only with median pivot', 'Only for integers'], correctIndex: 1, explanation: 'Quick Sort is not stable because the partitioning step can change the relative order of equal elements.' },
    { question: 'What is the space complexity (stack depth) of Quick Sort?', options: ['O(1)', 'O(log n) average', 'O(n)', 'O(n²)'], correctIndex: 1, explanation: 'Quick Sort uses O(log n) stack space on average for recursion, O(n) in worst case (can be optimized to O(log n) with tail recursion).' },
    { question: 'Why is Quick Sort generally faster than Merge Sort in practice?', options: ['It has better time complexity', 'It has better cache locality and in-place sorting', 'It uses less comparisons', 'It is always O(n log n)'], correctIndex: 1, explanation: "Quick Sort's in-place nature and good cache locality make it faster despite similar asymptotic complexity." },
    { question: 'What is the space complexity of the partition function?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctIndex: 0, explanation: 'Partition works in-place with just a few variables, requiring O(1) extra space.' },
  ],
  selection: [
    { question: 'What is the time complexity of Selection Sort in all cases?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correctIndex: 2, explanation: 'Selection Sort always performs n(n-1)/2 comparisons regardless of input order.' },
    { question: 'What is the main advantage of Selection Sort over Bubble Sort?', options: ['It is faster', 'It makes O(n) swaps vs O(n²)', 'It is stable', 'It is adaptive'], correctIndex: 1, explanation: 'Selection Sort makes at most n-1 swaps, while Bubble Sort makes O(n²) swaps in worst case.' },
    { question: 'Is Selection Sort stable?', options: ['Yes', 'No', 'Only in best case', 'Only for integers'], correctIndex: 1, explanation: 'Selection Sort is not stable because swapping can move an element past equal elements.' },
    { question: 'How many swaps does Selection Sort perform in worst case?', options: ['n-1', 'n(n-1)/2', 'n', 'n²'], correctIndex: 0, explanation: 'Selection Sort always makes exactly n-1 swaps, one per pass through the array.' },
    { question: 'What is the space complexity of Selection Sort?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], correctIndex: 0, explanation: 'Selection Sort sorts in-place with constant extra space.' },
  ],
  insertion: [
    { question: 'What is the best-case time complexity of Insertion Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], correctIndex: 0, explanation: 'When already sorted, each element comparison fails immediately, giving O(n).' },
    { question: 'What is the worst-case time complexity of Insertion Sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2^n)'], correctIndex: 2, explanation: 'When reverse sorted, each element must shift all previously sorted elements.' },
    { question: 'Why is Insertion Sort efficient for nearly sorted arrays?', options: ['It uses binary search', 'Few elements need to shift far', 'It only makes O(n) comparisons', 'It uses divide and conquer'], correctIndex: 1, explanation: 'Near the front, elements are mostly in place, so the inner while loop runs very few iterations.' },
    { question: 'What makes Insertion Sort an "online" algorithm?', options: ['It works on the internet', 'It can sort elements as they arrive one at a time', 'It requires all data upfront', 'It uses networking'], correctIndex: 1, explanation: 'Insertion Sort can process elements one at a time, inserting each into the already-sorted portion.' },
    { question: 'Is Insertion Sort stable?', options: ['Yes', 'No', 'Only for integers', 'Only in best case'], correctIndex: 0, explanation: 'Insertion Sort is stable because it inserts elements after equal elements (arr[j] > key, not >=).' },
  ],
  heap: [
    { question: 'What is the time complexity of Heap Sort in all cases?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], correctIndex: 1, explanation: 'Heap Sort has guaranteed O(n log n) performance: O(n) to build heap, O(n log n) to extract.' },
    { question: 'What is the space complexity of Heap Sort?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], correctIndex: 0, explanation: 'Heap Sort sorts in-place with O(1) extra space (no recursion, no extra arrays).' },
    { question: 'What data structure does Heap Sort use?', options: ['Stack', 'Queue', 'Binary Heap', 'Binary Search Tree'], correctIndex: 2, explanation: 'Heap Sort uses a binary heap (max-heap) to efficiently find and extract the maximum element.' },
    { question: 'How long does it take to build a heap from an array of n elements?', options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(n²)'], correctIndex: 0, explanation: 'Building a heap using the bottom-up approach takes O(n) time, not O(n log n).' },
    { question: 'Is Heap Sort stable?', options: ['Yes', 'No', 'Only for integers', 'Only in best case'], correctIndex: 1, explanation: 'Heap Sort is not stable because heap operations can rearrange equal elements.' },
  ],
};

export const GRAPH_QUIZZES: Record<string, QuizQuestion[]> = {
  bfs: [
    { question: 'What data structure does BFS primarily use?', options: ['Stack', 'Queue', 'Priority Queue', 'Array'], correctIndex: 1, explanation: 'BFS uses a queue to process nodes in FIFO order, ensuring level-by-level traversal.' },
    { question: 'What is the time complexity of BFS?', options: ['O(V)', 'O(E)', 'O(V + E)', 'O(V log V)'], correctIndex: 2, explanation: 'BFS visits each node once (O(V)) and examines each edge once (O(E)), giving O(V+E).' },
    { question: 'What type of graph is BFS best suited for finding shortest paths?', options: ['Weighted graphs', 'Unweighted graphs', 'Directed graphs only', 'Complete graphs'], correctIndex: 1, explanation: 'BFS finds the shortest path in unweighted graphs because it explores level by level.' },
    { question: 'What is the space complexity of BFS in worst case?', options: ['O(1)', 'O(log V)', 'O(V)', 'O(V+E)'], correctIndex: 2, explanation: 'In worst case (e.g., star graph), BFS queue may hold most of the nodes: O(V).' },
    { question: 'Can BFS be used for cycle detection?', options: ['Yes', 'No', 'Only in directed graphs', 'Only in trees'], correctIndex: 0, explanation: 'BFS can detect cycles: if we encounter a visited node that is not the parent, there is a cycle.' },
  ],
  dfs: [
    { question: 'What data structure does DFS primarily use?', options: ['Queue', 'Stack', 'Priority Queue', 'Hash Table'], correctIndex: 1, explanation: 'DFS uses a stack (or recursion) to process nodes in LIFO order, going deep first.' },
    { question: 'What is the time complexity of DFS?', options: ['O(V)', 'O(E)', 'O(V + E)', 'O(V log V)'], correctIndex: 2, explanation: 'DFS visits each node once and examines each edge once: O(V+E).' },
    { question: 'What is DFS best used for?', options: ['Shortest path in unweighted graphs', 'Cycle detection and topological sorting', 'Finding shortest path in weighted graphs', 'Minimum spanning tree'], correctIndex: 1, explanation: 'DFS is ideal for cycle detection, topological sorting, and connectivity analysis.' },
    { question: 'What problem can occur with recursive DFS on very deep graphs?', options: ['Infinite loop', 'Stack overflow', 'Memory leak', 'Segmentation fault'], correctIndex: 1, explanation: 'Recursive DFS on a graph with thousands of nodes may cause call stack overflow.' },
    { question: 'Does DFS guarantee finding the shortest path?', options: ['Yes', 'No', 'Only in trees', 'Only in complete graphs'], correctIndex: 1, explanation: 'DFS does not guarantee shortest path because it goes deep before exploring alternative paths.' },
  ],
  dijkstra: [
    { question: 'Why does Dijkstra use a priority queue?', options: ['To visit nodes in FIFO order', 'To always expand the closest node first', 'To implement LIFO behavior', 'To reduce memory usage'], correctIndex: 1, explanation: 'A priority queue allows Dijkstra to always extract the node with minimum distance, ensuring the shortest path is found.' },
    { question: "What is the time complexity of Dijkstra's algorithm with a binary heap?", options: ['O(V²)', 'O(V + E)', 'O(V + E log V)', 'O(E log V)'], correctIndex: 2, explanation: 'With binary heap: O(V log V) for extract-min operations + O(E log V) for priority queue updates = O(V + E log V).' },
    { question: 'What is the main limitation of Dijkstra?', options: ['It only works on trees', 'It does not work with negative edge weights', 'It requires complete graphs', 'It is very slow'], correctIndex: 1, explanation: "Dijkstra assumes that once a node's distance is finalized, it cannot be improved. Negative edges can violate this assumption." },
    { question: "What happens to Dijkstra's complexity without a priority queue?", options: ['O(V²)', 'O(V + E)', 'O(E log V)', 'O(V log V)'], correctIndex: 0, explanation: 'Without a priority queue, finding the minimum distance node takes O(V) each time, giving O(V²) total.' },
    { question: 'Can Dijkstra handle graphs with cycles?', options: ['Yes, with non-negative weights', 'No', 'Only simple cycles', 'Only directed cycles'], correctIndex: 0, explanation: 'Dijkstra works correctly on graphs with cycles as long as all edge weights are non-negative.' },
  ],
};
